config/routes.rb
Widgets::Application.routes.draw do
  resources :widgets

  root :to => "widgets#index"

end

app/models/widget.rb
class Widget < ActiveRecord::Base
  validates_presence_of :widget_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_filter :load

  def load
    @widgets = Widget.all
    @widget = Widget.new
	flash[:notice] = ''
  end


  # GET /widgets
  # GET /widgets.xml
  def index
    #@widgets = Widget.all

#    respond_to do |format|
#      format.html # index.html.erb
#      format.xml  { render :xml => @widgets }
#    end
  end

  # GET /widgets/1
  # GET /widgets/1.xml
  def show
    @widget = Widget.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
	  format.js
      format.xml  { render :xml => @widget }
    end
  end

  # GET /widgets/new
  # GET /widgets/new.xml
  def new
    @widget = Widget.new

    respond_to do |format|
      format.html # new.html.erb
	  format.js
      format.xml  { render :xml => @widget }
    end
  end

  # GET /widgets/1/edit
  def edit
    @widget = Widget.find(params[:id])
  end

  # POST /widgets
  # POST /widgets.xml
  def create
    @widget = Widget.new(params[:widget])

    respond_to do |format|
      if @widget.save
        format.html { redirect_to(@widget, :notice => 'Widget was successfully created.') }
		format.js { flash[:notice] = 'Widget was successfully created.' }
        format.xml  { render :xml => @widget, :status => :created, :location => @widget }
      else
        format.html { render :action => "new" }
		format.js 
        format.xml  { render :xml => @widget.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /widgets/1
  # PUT /widgets/1.xml
  def update
    @widget = Widget.find(params[:id])

    respond_to do |format|
      if @widget.update_attributes(params[:widget])
        format.html { redirect_to(@widget, :notice => 'Widget was successfully updated.') }
		format.js { flash[:notice] = 'Widget was successfully updated.' }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
		format.js 
        format.xml  { render :xml => @widget.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /widgets/1
  # DELETE /widgets/1.xml
  def destroy
    @widget = Widget.find(params[:id])
    @widget.destroy

    respond_to do |format|
      format.html { redirect_to(widgets_url) }
	  format.js { flash[:notice] = 'Widget was successfully destroyed.' }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Widgets</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag 'jquery-1.4.3.min', 'rails', 'application' %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="outer-body">

    <div id="menu-bar">
       <div id="menu-item">
	     <%= link_to 'Home', root_url, { :title => 'Go to home page'} %>
  	   </div>
    </div>
    <div id="content">
	  <%#= yield %> 
	  <%= render :partial => "index" %>
    </div>
    <div id="display">
    </div>

    <div id="outer-body-bottom-center">
       <script type="text/javascript" language="javascript">
       <!-- Begin
	      writeBottom("No");
      //-->
       </script>
    </div> <!-- end outer-body-bottom-center -->
   
  <div> <!--end outer-body --></body>

</body>
</html>

app/views/widgets/_create.html.erb
<p>
  <b>New widget '<%= name %>' successfully created.</b>
</p>

app/views/widgets/_destroy.html.erb
<p>
  <b>Widget '<%= name %>' successfully removed.</b>
</p>

app/views/widgets/_form.html.erb
<%= form_for(@widget, :remote => true) do |f| %>
  <% if @widget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@widget.errors.count, "error") %> prohibited this widget from being saved:</h2>

      <ul>
      <% @widget.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :widget_name %><br />
    <%= f.text_field :widget_name %>
  </div>
  <div class="field">
    <%= f.label :widget_desc %><br />
    <%= f.text_field :widget_desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/widgets/_index.html.erb
<% @widgets = Widget.all %>

<% if notice %>
  <p id="flash_notice"><%= flash[:notice] %></p>
<% end %>
<% if flash[:error] %>
  <p id="flash_errors"><%= flash[:error] %></p>
<% end %>

<table>
  <tr>
    <th>Widget name</th>
    <th>Widget desc</th>
  </tr>

<% @widgets.each do |widget| %>
  <tr>
    <td><%= link_to widget.widget_name, widget, :remote => true %></td>
    <td><%= widget.widget_desc %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Create a New Widget', new_widget_path, :remote => true %>

app/views/widgets/_new.html.erb
<%= render 'form' %>

app/views/widgets/_test.html.erb
<i>this is a test</i>

app/views/widgets/_update.html.erb
<p>
  <b>Widget '<%= name %>' successfully updated.</b>
</p>

app/views/widgets/create.js.erb
$("#display").html("<%= escape_javascript(render 'create', :name => @widget.widget_name) %>")
$("#content").html("<%= escape_javascript(render 'index') %>")

app/views/widgets/edit.js.erb
$("#display").html("<%= escape_javascript(render 'edit') %>")
$("#content").html("<%= escape_javascript(render 'index') %>")

app/views/widgets/index.html.erb
<table>
  <tr>
    <th>Widget name</th>
    <th>Widget desc</th>
  </tr>

<% @widgets.each do |widget| %>
  <tr>
    <td><%= link_to widget.widget_name, widget, :remote => true %></td>
    <td><%= widget.widget_desc %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Create a New Widget', new_widget_path, :remote => true %>

app/views/widgets/new.html.erb
<h1>New widget</h1>

<%= render 'form' %>

<%= link_to 'Back', widgets_path %>

app/views/widgets/new.js.erb
$("#display").html("<%= escape_javascript(render 'new') %>")
$("#content").html("<%= escape_javascript(render 'index') %>")

app/views/widgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Widget name:</b>
  <%= @widget.widget_name %>
</p>

<p>
  <b>Widget desc:</b>
  <%= @widget.widget_desc %>
</p>


<%= link_to 'Edit', edit_widget_path(@widget) %> |
<%= link_to 'Back', widgets_path %>

app/views/widgets/update.js.erb
$("#display").html("<%= escape_javascript(render( 'update', :name => @widget.widget_name) ) %>")
$("#content").html("<%= escape_javascript(render 'index') %>")